### ISSUE TITLE
AttenuationAndPlaySoundOrFreq description in device.yml is incorrect for address 37

### ISSUE THREAD

**Issue by NeuroThom** [harp-tech/device.soundcard#23]
Description for address 37: 
```
AttenuationAndPlaySoundOrFreq:
    <<: *attenuation
    address: 37
    length: 3
    description: Configures attenuation and plays sound index [Att R] [Att L] [Index]
```
However, sending a ushort[] with attenuation value of 0 (e.g. [0,0,10] throws an invalid write error. 
This is because the index cannot be 0 and the device.yml description shows the incorrect order for the array.
